//! Embeds the offline manuals for `peek docs`.
//!
//! `crates/cli/docs/*.md` is a copy of the canonical `docs/` directory, kept in
//! sync by `scripts/sync-cli-docs.py` so the crate is publishable on its own
//! (BLUEPRINT §7.6). This script lists whatever manuals exist there and writes
//! `$OUT_DIR/embedded_docs.rs`, a table of `(name, path, include_str!(…))`.
//! `src/docs.rs` maps the 16 advertised topics onto that table and falls back
//! to a short built-in text for a topic whose file is missing, so the binary
//! always builds and every topic always resolves.

use std::{
    env,
    error::Error,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

fn main() -> Result<(), Box<dyn Error>> {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let docs = manifest.join("docs");
    // A directory path makes Cargo rescan it for added, removed or edited files.
    println!("cargo:rerun-if-changed=docs");
    println!("cargo:rerun-if-changed=build.rs");

    let mut manuals = Vec::new();
    if docs.is_dir() {
        for entry in fs::read_dir(&docs)? {
            let path = entry?.path();
            if is_manual(&path) {
                let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
                    continue;
                };
                // include_str! needs UTF-8; skip (and report) anything else.
                if fs::read_to_string(&path).is_err() {
                    println!(
                        "cargo:warning=skipping {}: not UTF-8, so it cannot be embedded",
                        path.display()
                    );
                    continue;
                }
                manuals.push((stem.to_owned(), path));
            }
        }
    }
    manuals.sort();

    let mut out = String::from(
        "// @generated by crates/cli/build.rs from crates/cli/docs/*.md. Do not edit.\n\
         /// Embedded manuals: (file stem, path relative to the crate, Markdown).\n\
         pub(crate) static EMBEDDED: &[(&str, &str, &str)] = &[\n",
    );
    for (stem, path) in &manuals {
        let absolute = path.canonicalize()?;
        let absolute = absolute
            .to_str()
            .ok_or_else(|| format!("{} is not valid UTF-8", absolute.display()))?;
        writeln!(
            out,
            "    ({stem:?}, {rel:?}, include_str!({absolute:?})),",
            rel = format!("docs/{stem}.md"),
        )?;
    }
    out.push_str("];\n");
    let target = PathBuf::from(env::var("OUT_DIR")?).join("embedded_docs.rs");
    fs::write(target, out)?;
    Ok(())
}

fn is_manual(path: &Path) -> bool {
    path.extension().is_some_and(|e| e == "md")
        && fs::symlink_metadata(path).is_ok_and(|m| m.file_type().is_file())
}
