#!/bin/sh
# Regenerates Packages/PeekKit/Sources/PeekDrawing/SampleDrawings.swift from the *.js files next to this
# script. PeekKit has no resource bundle, so the samples are embedded as Swift string literals; the
# PeekDrawing tests fail when the embedded copies and these files differ.
set -eu
here=$(cd "$(dirname "$0")" && pwd)
out="$here/../../Packages/PeekKit/Sources/PeekDrawing/SampleDrawings.swift"
tmp="$out.tmp"
{
  echo '// Generated by apps/mac/Samples/drawings/embed.sh from apps/mac/Samples/drawings/*.js. Do not edit.'
  echo 'import Foundation'
  echo ''
  echo '/// The sample drawings (visual.md A8 adapted per BLUEPRINT §0.1, plus the Simulation deck).'
  echo 'public enum SampleDrawings {'
  echo '    public struct Sample: Sendable, Hashable, Identifiable {'
  echo '        public var id: String { filename }'
  echo '        /// e.g. `cassette.js`'
  echo '        public let filename: String'
  echo '        public let source: String'
  echo '        public var data: Data { Data(source.utf8) }'
  echo '    }'
  echo ''
  echo '    /// The drawing Simulation shows by default.'
  echo '    public static var simulation: Sample { deck }'
  echo ''
  names=""
  for file in "$here"/*.js; do
    base=$(basename "$file" .js)
    name=$(printf '%s' "$base" | awk -F- '{ out=$1; for (i = 2; i <= NF; i++) out = out toupper(substr($i,1,1)) substr($i,2); print out }')
    names="$names $name"
    echo "    public static let $name = Sample(filename: \"$base.js\", source: #\"\"\""
    cat "$file"
    echo '"""#)'
    echo ''
  done
  printf '    public static let all: [Sample] = ['
  first=1
  for name in $names; do
    if [ $first -eq 1 ]; then printf '%s' "$name"; first=0; else printf ', %s' "$name"; fi
  done
  echo ']'
  echo '}'
} > "$tmp"
mv "$tmp" "$out"
echo "wrote $out"
